[versions]
agp = "8.7.2"
kotlin = "2.1.0"
activityCompose = "1.9.3"
libphonenumber = "8.13.50"
material3 = "1.3.1"
ktx = "1.15.0"
spotless = "6.25.0"
kotlin-compatibility = "0.16.3"
dokka = "2.0.0"
gradleMavenPublish = "0.30.0"
nmcp = "0.0.9"
compose = "1.7.5"
junitVersion = "4.13.2"
androidxJunit = "1.2.1"
truth = "1.4.4"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

junit = { module = "junit:junit", version.ref = "junitVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-compatibility" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublish" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
