[versions]
agp = "8.13.2"
kotlin = "2.3.10"
compose-multipatform = "1.8.2"
activityCompose = "1.12.4"
libphonenumber = "9.0.24"
material3 = "1.4.0"
ktx = "1.17.0"
spotless = "8.2.1"
kotlin-compatibility = "0.18.1"
dokka = "2.1.0"
gradleMavenPublish = "0.36.0"
nmcp = "1.4.1"
compose = "1.10.3"
junitVersion = "4.13.2"
androidxJunit = "1.3.0"
truth = "1.4.5"

android-compileSdk = "36"
android-minSdk = "23"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "compose" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

junit = { module = "junit:junit", version.ref = "junitVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multipatform" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-compatibility" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublish" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
