[versions]
agp = "8.13.0"
kotlin = "2.2.10"
activityCompose = "1.11.0"
libphonenumber = "9.0.14"
material3 = "1.3.2"
ktx = "1.17.0"
spotless = "7.2.1"
kotlin-compatibility = "0.18.1"
dokka = "2.0.0"
gradleMavenPublish = "0.34.0"
nmcp = "1.1.0"
compose = "1.9.2"
junitVersion = "4.13.2"
androidxJunit = "1.3.0"
truth = "1.4.5"

android-compileSdk = "36"
android-minSdk = "21"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

junit = { module = "junit:junit", version.ref = "junitVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-compatibility" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublish" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
