[versions]
agp = "8.3.2"
kotlin = "1.9.23"
accompanistSystemuicontroller = "0.34.0"
activityCompose = "1.9.0"
libphonenumber = "8.13.34"
material3 = "1.2.1"
composeCompiler = "1.5.11"
ktx = "1.13.0"
spotless = "6.25.0"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }